version: '{build}'
image: Visual Studio 2017

environment:
  matrix:
  - TARGET: dotnet
  - TARGET: native

install:
  - ps: |
      if ($env:Target -eq "native") {
        Invoke-WebRequest https://files.fusetools.com/tooling/iyVp8kwQ0vLn-mesa-17.2.3.500.zip -OutFile mesa.zip
        Expand-Archive mesa.zip mesa
      }

build_script:
  - npm pack

artifacts:
  - path: '*.tgz'

before_test:
  - ps: |
      if ($env:Target -eq "native") {
        Get-ChildItem -Path lib -Recurse -Include *Test.unoproj | Select-Object -ExpandProperty DirectoryName | Foreach-Object {
          $buildDir = Join-Path $_ build\Test\Native
          New-Item -Force -ItemType directory -Path $buildDir | Out-Null
          Copy-Item -Path mesa\x64\opengl32.dll -Destination (Join-Path $buildDir opengl32.dll)
        }
      }

test_script:
  - nunit3-console
      src\testing\Uno.TestRunner.Tests\bin\Release\Uno.TestRunner.Tests.dll
      src\ux\Uno.UX.Markup.AST\Tests\bin\Release\Uno.UX.Markup.AST.Tests.dll
      src\ux\Uno.UX.Markup.UXIL\Tests\bin\Release\Uno.UX.Markup.UXIL.Tests.dll
  - bash scripts\test.sh %TARGET%
