os: osx
osx_image: xcode9.2
language: csharp
mono: latest

env:
  matrix:
    - TARGET=dotnet
    - TARGET=native

before_script:
  - ulimit -c unlimited -S
  - rm -rf /cores/core.*

script:
  - scripts/build.sh
  - bin/uno test --target=$TARGET lib
  - bin/uno test-gen lib /tmp/PackageCompilationTest
  - bin/uno build --target=$TARGET --no-strip /tmp/PackageCompilationTest

after_failure:
  - for c in $(ls /cores/core.*); do
      lldb -c $c -o "bt all" -b;
    done
