os: osx
osx_image: xcode9.2
language: csharp
mono: latest

env:
  matrix:
    - TARGET=dotnet
    - TARGET=native

before_script:
  - ulimit -c unlimited -S
  - rm -rf /cores/core.*

script:
  - scripts/build.sh
  - scripts/test.sh $TARGET

after_failure:
  - for c in $(ls /cores/core.*); do
      lldb -c $c -o "bt all" -b;
    done
